import React,{useState} from 'react'
import {Target,MapPinned,Download,ArrowRight,AlertTriangle} from 'lucide-react'
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts'
import GeoMap from './GeoMap'
import {targets,drillholes,elements} from './mockData'
type T=(typeof targets)[number]
type Page='map'|'targets'|'drillholes'|'geoscience'|'qaqc'
type Props={role:'geologist'|'executive',onTarget:(target:T)=>void,onNavigate:(page:Page)=>void}
const programs=[{name:'Central Porphyry',mineral:'Cu-Mo',budget:1200,spent:864,planned:360,drilled:318,risks:2,progress:63},{name:'Northern Gold',mineral:'Au',budget:820,spent:664,planned:180,drilled:152,risks:1,progress:71},{name:'Eastern Skarn',mineral:'Fe-Cu',budget:510,spent:449,planned:125,drilled:92,risks:2,progress:42}]
const logs=[{id:'DH-021',depth:420,logged:420},{id:'DH-022',depth:365,logged:337},{id:'DH-023',depth:510,logged:366},{id:'DH-024',depth:450,logged:0}]
const labs=[{batch:'CU-081',mineral:'Cu/Mo',samples:42,stage:'Overdue'},{batch:'AU-044',mineral:'Au',samples:27,stage:'In laboratory'},{batch:'FE-026',mineral:'Fe/Cu',samples:19,stage:'In laboratory'}]
const fmt=(n:number)=>n.toLocaleString('en-US',{maximumFractionDigits:1})
function download(name:string,rows:Record<string,string|number>[]){const keys=Object.keys(rows[0]||{});const q=(v:unknown)=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=[keys.map(q).join(','),...rows.map(r=>keys.map(k=>q(r[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();URL.revokeObjectURL(url)}
function Kpi({label,value,detail}:{label:string,value:string,detail:string}){return <div className="role-kpi"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Geo({onTarget,onNavigate}:Omit<Props,'role'>){
 const [target,setTarget]=useState<T>(targets[0]);const [minScore,setMinScore]=useState(70);const [mineral,setMineral]=useState('All')
 const shortlisted=targets.filter(t=>t.aiScore>=minScore&&(mineral==='All'||t.commodity.includes(mineral)))
 const backlog=logs.reduce((n,h)=>n+h.depth-h.logged,0)
 return <div className="role-dashboard">
  <div className="role-intro"><div><small>GEOLOGIST / FIELD WORKBENCH</small><h1>Geoscience Workbench</h1><p>Interpret exploration evidence, log drillholes and prioritize target validation.</p></div><button className="role-action" onClick={()=>onNavigate('map')}><MapPinned size={16}/> Full GIS map <ArrowRight size={15}/></button></div>
  <div className="role-kpi-grid"><Kpi label="Prospectivity targets" value={String(targets.length)} detail="Illustrative prospects"/><Kpi label="High scoring targets" value={String(targets.filter(x=>x.aiScore>=80).length)} detail="Score 80+ · synthetic"/><Kpi label="Logging backlog" value={fmt(backlog)+' m'} detail="Incomplete logging metres"/><Kpi label="Assay batches" value={String(labs.length)} detail="One fictional overdue batch"/></div>
  <div className="role-two-columns"><section className="panel"><div className="role-head"><h2>Prospectivity map</h2><p>OpenStreetMap basemap · fictional target coordinates</p></div><GeoMap selectedId={target.id} onSelect={setTarget}/><div className="role-target-detail"><b>{target.id} · {target.name}</b><p>{target.rationale}</p><button className="role-action" onClick={()=>onTarget(target)}>Inspect evidence <ArrowRight size={14}/></button></div></section>
  <section className="panel"><div className="role-head"><h2>Target screening</h2><p>Filter simulated scores and target commodities</p></div><div className="role-filter-row"><label>Commodity<select value={mineral} onChange={e=>setMineral(e.target.value)}><option>All</option><option>Cu</option><option>Au</option><option>Fe</option></select></label><label>Minimum score: {minScore}<input type="range" min="0" max="100" step="5" value={minScore} onChange={e=>setMinScore(+e.target.value)}/></label></div><div className="role-target-list">{shortlisted.map(t=><button key={t.id} className={target.id===t.id?'selected':''} onClick={()=>setTarget(t)}><b>{t.aiScore}</b><span>{t.name}<small>{t.id} · {t.commodity} · {t.stage}</small></span><ArrowRight size={14}/></button>)}{!shortlisted.length&&<p>No targets match.</p>}</div><button className="role-export" onClick={()=>download('demo-targets',shortlisted.map(t=>({id:t.id,name:t.name,mineral:t.commodity,score:t.aiScore,action:t.action})))}><Download size={14}/> Export shortlist CSV</button></section></div>
  <div className="role-two-columns role-bottom"><section className="panel"><div className="role-head"><h2>Drillhole logging queue</h2><button className="role-export" onClick={()=>onNavigate('drillholes')}>Drillholes <ArrowRight size={14}/></button></div><div className="role-table-scroll"><table className="role-table"><thead><tr><th>Hole</th><th>Depth</th><th>Logged</th><th>Completion</th></tr></thead><tbody>{logs.map(h=><tr key={h.id}><td>{h.id}</td><td>{h.depth} m</td><td>{h.logged} m</td><td><div className="role-meter"><i style={{width:(100*h.logged/h.depth)+'%'}}/></div>{fmt(100*h.logged/h.depth)}%</td></tr>)}</tbody></table></div></section><section className="panel"><div className="role-head"><h2>Sample & laboratory queue</h2><button className="role-export" onClick={()=>onNavigate('qaqc')}>Review QA/QC <ArrowRight size={14}/></button></div>{labs.map(x=><div className="role-lab-row" key={x.batch}><div><b>{x.batch} · {x.mineral}</b><small>{x.samples} samples</small></div><span className={x.stage==='Overdue'?'role-critical':'role-warning'}>{x.stage}</span></div>)}<p className="role-notice"><AlertTriangle size={15}/> All assays and status flags are fictitious.</p></section></div>
 </div>
}
function Executive({onNavigate}:Omit<Props,'role'|'onTarget'>){
 const [scope,setScope]=useState('All programs');const visible=programs.filter(p=>scope==='All programs'||p.name===scope)
 const totals=visible.reduce((a,p)=>({budget:a.budget+p.budget,spent:a.spent+p.spent,planned:a.planned+p.planned,drilled:a.drilled+p.drilled,risks:a.risks+p.risks}),{budget:0,spent:0,planned:0,drilled:0,risks:0})
 return <div className="role-dashboard"><div className="role-intro"><div><small>EXECUTIVE / PORTFOLIO</small><h1>Exploration Portfolio</h1><p>Portfolio drilling progress, risk and cost exposure for management review.</p></div><label className="role-scope">Project<select value={scope} onChange={e=>setScope(e.target.value)}><option>All programs</option>{programs.map(p=><option key={p.name}>{p.name}</option>)}</select></label></div>
  <div className="role-kpi-grid"><Kpi label="Allocated budget" value={'$'+fmt(totals.budget)+'k'} detail="Illustrative allocation in USD"/><Kpi label="Budget consumed" value={fmt(100*totals.spent/totals.budget)+'%'} detail={'$'+fmt(totals.spent)+'k spent'}/><Kpi label="Drilling performance" value={fmt(100*totals.drilled/totals.planned)+'%'} detail={totals.drilled+' / '+totals.planned+' m'}/><Kpi label="Open portfolio risks" value={String(totals.risks)} detail="Fictional management exceptions"/></div>
  <div className="role-two-columns"><section className="panel"><div className="role-head"><h2>Budget vs expenditure</h2><p>USD thousands, synthetic program financials</p><button className="role-export" onClick={()=>download('demo-portfolio',visible.map(x=>({project:x.name,budget_thousand_usd:x.budget,spent_thousand_usd:x.spent,progress_percent:x.progress})))}><Download size={14}/> Export CSV</button></div><div className="role-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={visible}><CartesianGrid stroke="#254334" strokeDasharray="3 4" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10,fill:'#b1c6b9'}}/><YAxis tick={{fontSize:10,fill:'#b1c6b9'}}/><Tooltip contentStyle={{background:'#0f2419',border:'1px solid #33523c'}}/><Bar dataKey="budget" name="Budget $k" fill="#75978a" radius={[4,4,0,0]}/><Bar dataKey="spent" name="Spent $k" fill="#65d7a6" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><p className="role-notice">Remaining allocation: $ {fmt(totals.budget-totals.spent)}k · illustrative only.</p></section>
  <section className="panel"><div className="role-head"><h2>Management attention</h2><p>Risks and project delivery exceptions</p></div>{visible.map(p=><div key={p.name} className="role-risk-row"><b>{p.name}</b><span className={p.risks>1?'role-critical':'role-warning'}>{p.risks} risks</span><small>{p.mineral} · {p.drilled}/{p.planned} m drilled · {p.progress}% completion</small></div>)}<button className="role-action" onClick={()=>onNavigate('qaqc')}>Investigate quality issues <ArrowRight size={14}/></button></section></div>
  <section className="panel role-bottom"><div className="role-head"><h2>Program portfolio</h2><p>Management comparison table</p></div><div className="role-table-scroll"><table className="role-table"><thead><tr><th>Project</th><th>Commodity</th><th>Completion</th><th>Drilled</th><th>Budget used</th><th>Risks</th></tr></thead><tbody>{visible.map(p=><tr key={p.name}><td><b>{p.name}</b></td><td>{p.mineral}</td><td><div className="role-meter"><i style={{width:p.progress+'%'}}/></div>{p.progress}%</td><td>{p.drilled}/{p.planned} m</td><td>{fmt(100*p.spent/p.budget)}%</td><td>{p.risks}</td></tr>)}</tbody></table></div></section>
  <div className="role-quick-links"><button onClick={()=>onNavigate('targets')}><Target size={16}/> Target intelligence <ArrowRight size={14}/></button><button onClick={()=>onNavigate('drillholes')}>Drilling progress <ArrowRight size={14}/></button><button onClick={()=>onNavigate('geoscience')}>Geochemistry <ArrowRight size={14}/></button></div>
 </div>
}
export default function RoleDashboard({role,onTarget,onNavigate}:Props){return role==='geologist'?<Geo onTarget={onTarget} onNavigate={onNavigate}/>:<Executive onNavigate={onNavigate}/>}
